### ISSUE TITLE
Post markdown support

### ISSUE THREAD

**Issue by AndreasElia** [bitporch/laravel-firefly#128]
Could be a useful feature with a config option to enable/disable as well as choose between markdown options.

**Comment by byCedric** [comment]
Maybe it's nice to have a sort of Post-process plugin. So markdown can be a great example of such a plugin, but also stuff like sentiment checks could be handy-dandy right?

**Comment by byCedric** [comment]
Or even translating stuff...

**Comment by AndreasElia** [comment]
Barebones forum, this would be a separate package.
