### ISSUE TITLE
Missing friendly error message for guests on discussion create

### ISSUE THREAD

**Issue by deleugpn** [bitporch/laravel-firefly#179]
I wrote this test (https://github.com/bitporch/laravel-forum/blob/failing-tests/tests/Integration/PostTest.php#L32) that needs to be addressed in the core code. Right now if you try to create a discussion without logging in you just get a `Trying to get property of non-object` exception.

**Comment by AndreasElia** [comment]
You should check `auth.login` or whatever the name of the **default** Laravel auth routes are. We won't be handling any auth redirection ourselves and it will all be down to whatever middleware is enabled.

**Comment by deleugpn** [comment]
I didn't fully worked on how to deal with the tests because I was waiting to know how it would be handled in the source-code level. Maybe we don't even check for redirection in the tests, but we need to at least check for an error message or status 302 (regardless of the destination).

**Comment by Riari** [comment]
If/when policies are working properly, attempting to create a discussion as a guest should result in a 403 from the API or a 302 from the web route. We don't need to implement any manual checks.

**Comment by AndreasElia** [comment]
I managed to fix policies a few days ago (a parameter or two was missing). Haven't tested anything as a guest as of yet though.

**Comment by AndreasElia** [comment]
@Dylan-DPC does this still apply?

**Comment by Dylan-DPC** [comment]
policies do not apply fo guest users. So probably have to include the route inside the auth middleware except for `index/show` part so that guests can see the discussion

**Comment by AndreasElia** [comment]
Closed as I feel this won't apply once the discussion policies are in place correctly.
