### ISSUE TITLE
Lumen compatibility

### ISSUE THREAD

**Issue by Riari** [bitporch/laravel-firefly#55]
We have the option of making this package compatible with Lumen since it only depends on Illuminate components, but if we want to do that, we need to consider a few things:

- Route definitions. Lumen uses a different router that doesn't support route grouping, so we may need to consider changing the way routes are defined.
- Separate service providers for Laravel and Lumen since some things can't be done by default (or at all) in Lumen.

There may be other stuff too, but those are the primary concerns IMO.

Edit: Alongside this, we should maybe consider a rename. Maybe `illuminate-forum`, or a more creative name à la Discourse, Flarum, etc.

**Comment by AndreasElia** [comment]
I'm a fan of supporting Lumen for sure (albeit after 1.0 launch).

As for naming, I agree that a different name would be great to have, I'll give it some thought (suggestions welcome).

**Comment by jordyvandomselaar** [comment]
"DeLorum"

**Comment by Riari** [comment]
Nevermind, this is a shit idea.

**Comment by jordyvandomselaar** [comment]
Took you long enough.
