### ISSUE TITLE
Make GroupPolicy toggleable per Group

### ISSUE THREAD

**Issue by Riari** [bitporch/laravel-firefly#8]
Since Policies are only designed to grant access after authentication, you might not always want certain methods from them to apply to your Groups.

In my package, I eventually solved that by adding a boolean column (`private`) to Categories (equivalent to your Groups) to indicate whether or not Policies should apply to them at all. I'd recommend doing something similar 👍 

(Here's the part where Connor barges in and tells me how horrible this idea is)

**Comment by ConnorVG** [comment]
The problem I have here is that we're debating a method of constraint for a system that is not yet decided upon – how do you know a user has the rights to X in the first place? Will this package enforce usage of a strict X / Y system or will it allow for something else?

I feel like this is going to end up in something like:
```
interface ForumAuthorisable
{
    const READ_GROUP = 0;

    public function hasForumAccess(int $permission) : bool;
}
```

Or even worse, considering I imagine we'd want per-x/y permissables.

I guess, what I'm trying to say is, let's draw the bridge before we attempt to cross it.

**Comment by Riari** [comment]
The point is simply that the Gate will give unauthenticated users a 403 before it even attempts to execute a Policy method, which is a problem no matter how you look at it - so I'm just suggesting a way of controlling that, which worked very well for me (though the implementation could no doubt be better).

**Comment by ConnorVG** [comment]
@Riari I see what you mean, there would need to be some sort of visibility identifier on the Group. Not all forums are fully private. It might be worth having some sort of access level column.

**Comment by Riari** [comment]
That would be taken care of in the Policy as normal. The package user can set certain Groups as Private, which at a minimum means they can only be viewed/interacted with by authenticated users - then write granular checks however they want to, referencing role/perm systems or whatever else they might have.

I think the biggest grey area with this is exactly where to draw the line with private vs. non-private. E.g. do we want this package to support the ability for guests to create Discussions or Posts (probably not, but it's worth considering since it's a common feature of forums).

**Comment by ConnorVG** [comment]
That's a good point to bring up, I quite like it. Nice perspective.

So my new question: do we even _need_ policies?

**Comment by Riari** [comment]
I'd say we do, only because some kind of permission system is an inevitable requirement and it makes more sense to use a native Laravel feature that can be used to plug in other permission systems than to try writing something fully bespoke.

Could go a step further and provide some kind of default ACL system alongside it, but I think most people would want to implement it themselves or hook it up with whatever's in their app.

**Comment by ConnorVG** [comment]
@Riari this makes no sense, the policy is the provision to your permissable system – what could you possibly put inside of the policy function body to verify access without knowing the current ACL implementation?

**Comment by Riari** [comment]
Just return true or false and let the user override them. There's no way they can make sense by default, it's just about making it as straightforward as possible to change the default behaviour.

**Comment by Riari** [comment]
I mean, you can get somewhat close by returning false for actions that write to the DB and true for anything else, but there's no avoiding it being something the user will need to adjust.

**Comment by ConnorVG** [comment]
@Riari sorta my point – it's just shite at that point, it would make more sense to just include a command that stubs out the policies in the user's application instead.

`php artisan forum:policies`

**Comment by Riari** [comment]
Right, but what's it going to call without those stubs being there? Maybe a separate discussion is needed about package installation or possibly even the idea of a graphical installer. The point of this issue is about making Policies suitable for a forum, which isn't really difficult in itself.

**Comment by Dylan-DPC** [comment]
@ConnorVG we need to do both - allow this to be customisable by user as well as give a default policy. What say? (not sure how.. still thinking ;P )

**Comment by Riari** [comment]
I think the problem is that out-of-the-box policies aren't really possible without understanding the package user's application or how they're going to set categories up, so providing policy stubs is the only real option.

**Comment by Dylan-DPC** [comment]
Do we still need this? since we have moved policies to stubs and the policies will be in user space

**Comment by Riari** [comment]
Yeah, this is still relevant as it's a means of disabling the Gate on a per-category basis.

**Comment by Dylan-DPC** [comment]
Cool. We won't do this for first release. Will add it in the future

**Comment by Riari** [comment]
I would reconsider that because, without this, unauthenticated users won't even be able to see any categories regardless of how the policies are configured. At that point, it's only useful for people who want totally private forums.

**Comment by Dylan-DPC** [comment]
oh ya.. without authentication.. get it now..
